FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Phantom

### [Javadoc](http://cyberpwnn.github.io/Phantom/) - [Project](https://github.com/cyberpwnn/Phantom) - [Website](http://phantomapi.org/)

![](https://raw.githubusercontent.com/cyberpwnn/Phantom/master/phantom-medium.png)

The phantom api is an api designed to allow plugin developers to program structured, fast plugins with speed by abstracting common things usually needed for most plugins. The biggest part of Phantom is the Controller system, and the Data-clusters with Configurable objects. To get started working with phantom, find what you need below.