package com.volmit.phantom.api.module;

public enum ModuleOperation
{
	START,
	STOP,
	TEST,
	UNREGISTER_ALL,
	REGISTER_SERVICES,
	REGISTER_INSTANCES,
	REGISTER_COMMANDS,
	REGISTER_PERMISSIONS,
	REGISTER_CONFIGS,
}
